# Generated by Django 2.1 on 2018-10-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20180319_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
