# Generated by Django 2.1 on 2018-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_project_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isFunded',
            field=models.BooleanField(default=False),
        ),
    ]
